# -*- coding: utf-8 -*-
"""Exercício.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zDL3Rbs8u_cF4UyF0T4I-g-GfWAkia_c
"""

nome = input("Digite seu nome: ") #Salva o nome do usuário
print("Seja bem vindo(a)", nome, "!")
valor = float(input("Digite o valor da compra: ")) #Salva o valor digitado pelo usuário
parcelas = int(input("Digite o número de parcelas: "))
if parcelas == 1 :
    valor_parcela = valor * 0.95  # Desconto de 5% a vista
    print("O valor à vista é de", "R$", valor_parcela )
if parcelas == 2 or parcelas == 3 :
    valor_parcela = valor * 1.05  # Acrécimo de 5%
    print("O valor da parcela é de", "R$", valor_parcela )

if parcelas == 4 or parcelas == 5 :
    valor_parcela = valor * 1.10  # Acrécimo de 10%
    print("O valor da parcela é de", "R$", valor_parcela )

if parcelas == 6 or parcelas >= 7 :
    valor_parcela = valor * 1.15  # Acrécimo de 15%
    print("O valor da parcela é de", "R$", valor_parcela )